const PRODUCT_CATEGORY_FOOD = 'food'
const PRODUCT_CATEGORY_CLOTHING = 'clothing'

const LOCATION_TAX = {
  'CA': {
    rate: 0.0975, // 9.75%
    exempt: [PRODUCT_CATEGORY_FOOD]
  },
  'NY': {
    rate: 0.0875, // 8.875%
    exempt: [PRODUCT_CATEGORY_FOOD, PRODUCT_CATEGORY_CLOTHING]
  }
}

export { PRODUCT_CATEGORY_FOOD, PRODUCT_CATEGORY_CLOTHING, LOCATION_TAX }
